@extends('front.layout.app', ['title'=>null, 'description'=>null])
@section('content')
@include('front._include.home.1')
@include('front._include.home.2')
@include('front._include.home.exame_ouro')
@include('front._include.home.news_homepanel')
@include('front._include.home.4')
@include('front._include.home.8')
@include('front._include.home.9')
@include('front._include.home.3')
@include('front._include.home.7')
@include('front._include.home.5')
@include('front._include.home.10')
@endsection
